# Generated by Django 5.2.1 on 2025-10-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iphone',
            name='memori',
        ),
    ]
