# Generated by Django 5.2.1 on 2025-10-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_iphone_memori'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='memori',
            field=models.IntegerField(default=64),
        ),
    ]
