# Generated by Django 5.2.1 on 2025-10-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_iphone_memori'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iphone',
            name='gambar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
