# Generated by Django 5.2.1 on 2025-10-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_iphone_deskripsi_iphone_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subjek')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim pada')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
