# Generated by Django 5.2.1 on 2025-11-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iphone',
            options={'verbose_name': 'iPhone', 'verbose_name_plural': 'iPhone'},
        ),
        migrations.AddField(
            model_name='iphone',
            name='kode',
            field=models.CharField(default='IPHONE001', max_length=50, unique=True, verbose_name='Kode Produk'),
            preserve_default=False,
        ),
    ]
