"""
Django settings for spk_iphone project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#-u2w&h4cmxoi4$%xvz70=o7!#t)2y0z2v688pwqxl4p1$78*q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*",] 


# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'import_export', 
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spk_iphone.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spk_iphone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# settings.py

# settings.py

if os.getenv("RAILWAY_ENVIRONMENT"):
    # Jika running di Railway → pakai PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'spk_iphone',  # HARUS SAMA dengan nama database yang baru Anda buat
            'USER' : 'root',
            'PASSWORD' : '',
            'HOST': 'localhost',  # Umumnya 'localhost'
            'PORT': '3307',       # Port default MariaDB/MySQL
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Folder untuk file statis selama pengembangan
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Folder tujuan untuk file statis di lingkungan produksi
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Kirim
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'andikamelawi.net11@gmail.com'
EMAIL_HOST_PASSWORD = 'zlyz qnqo unyl pqtd'
DEFAULT_FROM_EMAIL = 'iPhone Recommender <noreply@iphonerecommender.com>'

# Optional: Konfigurasi import-export
IMPORT_EXPORT_USE_TRANSACTIONS = True

from django.utils.translation import gettext_lazy as _

JAZZMIN_SETTINGS = {
    "site_title": "iPhone Recommender Admin",
    "site_header": "iPhone Recommender Dashboard",
    "site_brand": "Admin",
    "welcome_sign": "Selamat datang di panel admin iPhone",
    "copyright": "© 2025 iPhone Recommender Project",
    "search_model": "main.Iphone",
    "user_avatar": None,

    # Ikon menu kiri
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.Iphone": "fas fa-mobile-alt",
        "main.Kriteria": "fas fa-sliders-h",
        "main.ContactMessage": "fas fa-envelope-open-text",
    },

    # Urutan menu
    "order_with_respect_to": ["main.Iphone", "main.Kriteria", "main.ContactMessage"],

    # Style
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "morph",  # kamu bisa coba 'flatly', 'darkly', 'cyborg', 'cosmo', dll
    "navbar": "navbar-light navbar-dark",
    "no_navbar_border": False,
    "sidebar": "sidebar-dark-light",
    "brand_colour": "navbar-dark",
    "accent": "accent-dark",
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar_collapse": False,
    "actions_sticky_top": True,
    "custom_css": "css/custom-jazzmin.css",
}
